In [224]:
# score: 0.82666


# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Imports

In [225]:
from xgboost import XGBRegressor, XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold
from sklearn.metrics import mean_absolute_error, roc_auc_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
import optuna

# Get data

In [226]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

X = train_data.copy()
X.drop(['id', 'target'], axis=1, inplace=True)

y = train_data['target']

no_id_test_data = test_data.drop('id', axis=1)

display(X.head())
display(y.head())

gravity    ph  osmo  cond  urea  calc
0    1.013  6.19   443  14.8   124  1.45
1    1.025  5.40   703  23.6   394  4.18
2    1.009  6.13   371  24.5   159  9.04
3    1.021  4.91   442  20.8   398  6.63
4    1.021  5.53   874  17.8   385  2.21

0    0
1    0
2    0
3    1
4    1
Name: target, dtype: int64

# Feature Engineering

In [227]:
display(X.columns)

def prepXy(df,X_label,y=None):
    
    data = df.drop(['gravity', 'ph', 'cond'], axis=1);
    return data, df, y
    
    selected_feat = []
    data = df.copy()
    
    # Feature Engineering
    
    
    # Ion product of calcium and urea
    data["ion_product"] = data["calc"] * data["urea"]

    # Calcium-to-urea ratio
    data["calcium_to_urea_ratio"] = data["calc"] / data["urea"]

    # Electrolyte balance
    data["electrolyte_balance"] = data["cond"] / (10 ** (-data["ph"]))

    # Osmolality-to-specific gravity ratio
    data["osmolality_to_sg_ratio"] = data["osmo"] / data["gravity"]

    # The product of osmolarity and density is created as a new property
    data['osmo_density'] = data['osmo'] * data['gravity']
    
    # ******************************************************************
    
    # Calculate ammonium concentration (assuming ammonium is not directly measured)
    data['ammonium_concentration'] = (data['gravity'] - 1.010) * (140 - (2 * data["ph"])) * 1.2

    # Calculate phosphate concentration (assuming phosphate is not directly measured)
    data['phosphate_concentration'] = (data['gravity'] - 1.010) * (32 - (0.06 * data["ph"]))

    # *****************************************************************
    
    data["gravity/ph"] = data["gravity"] / data["ph"]
    data["osmo/cond"] = data["osmo"] / data["cond"]
    data["gravity*ph"] = data["gravity"] * data["ph"]
    data["osmo*urea"] = data["osmo"] * data["urea"]
    data["cond_urea_ph"] = data["cond"] * data["urea"] / data["ph"]
    data["ph*osmo"] = data["ph"] * data["osmo"]
    data["cond*calc"] = data["cond"] * data["calc"]
    data["gravity/calc"] = data["gravity"] / data["calc"]

    # Split into features and target
    X_ret = data[X_label].values
    
    if y is None:
        y_ret = np.zeros(data.shape[0])
    else:
        y_ret = np.ravel(y)

    data.drop('ph', axis=1, inplace=True)

    
    data['target']=y_ret
    
    display(data.columns)
    
    sns.heatmap(data.corr())

    data.drop('target', axis=1, inplace=True)

    # Scaling dataset
    # scaler = MinMaxScaler()
    
    
    # scaler = StandardScaler()
    
    # X_ret = scaler.fit_transform(X_ret)

    return data,X_ret,y_ret


def feature_engineering(X):
    X.drop(['urea', 'osmo', 'ph', 'gravity'], axis=1, inplace=True)
    return X


print(X.count());

Index(['gravity', 'ph', 'osmo', 'cond', 'urea', 'calc'], dtype='object')

gravity    414
ph         414
osmo       414
cond       414
urea       414
calc       414
dtype: int64


# Remove Outliers

In [228]:
# Credit: KLYUSHNIK-ALEXSANDR

def outlier_removal(data , i):
    q1 = np.quantile(data[i] ,0.25)
    q3 = np.quantile(data[i] , 0.75)
    iqr = q3-q1
    lower_tail = q1 - 1.5*iqr
    upper_tail = q3 + 1.5*iqr
    
    
    for j in range(0, data[i].count()):
        if(data[i][j]>upper_tail or data[i][j]<lower_tail):
            data[i][j]=np.nan
            
    return data[i]

# Aggregate Features

In [229]:
def aggregate_features(X):
    
    # outlier_list = ['gravity', 'osmo', 'cond', 'urea', 'calc']
    outlier_list = ['calc', 'cond']
    for i in outlier_list:
        X[i]=outlier_removal(X ,i)
    
    my_imputer = SimpleImputer()
    X = pd.DataFrame(my_imputer.fit_transform(X))
    
    return X

# Preprocess Data

In [230]:
def preprocess_data(X, y=None):
    
    X = feature_engineering(X)
    
    X = aggregate_features(X)
    
    print('aleorcufd')
    # display(np.count_nonzero(np.isnan(X)))
    
    # display(X.columns)
    
    return X, y


'''preprocess data here'''
X, y = preprocess_data(X, y)
no_id_test_data, _ = preprocess_data(no_id_test_data)

display(X)

# cols_with_missing = [col for col in X.columns if X[col].isnull().any()]

# print(f'There are {len(cols_with_missing)} columns with missing values')

# for i in cols_with_missing:
#     print(i)
    
    
# print(X.count());



aleorcufd
aleorcufd


0     1
0    14.8  1.45
1    23.6  4.18
2    24.5  9.04
3    20.8  6.63
4    17.8  2.21
..    ...   ...
409  21.4  1.53
410  19.7  0.77
411  22.2  7.68
412  12.6  1.03
413   9.9  0.27

[414 rows x 2 columns]

# Hyperparameter Tuning

In [231]:
def optuna_study(X, y):

    def objective(trial):
        
        # For XGBRegressor
        # n_estimators = trial.suggest_int('n_estimators', 10, 1000)
        # learning_rate = trial.suggest_float('learning_rate', 0.01, 1.0)
        # max_depth = trial.suggest_int('max_depth', 1, 30)
        
        # rf = XGBClassifier(n_estimators=n_estimators,
        #                 learning_rate=learning_rate,
        #                 max_depth=max_depth)
        
        
        
        # For RandomForestClassifier
        # n_estimators = trial.suggest_int('n_estimators', 10, 1000)
        # max_leaf_nodes = trial.suggest_int('max_leaf_nodes', 2, 100)
        # max_depth = trial.suggest_int('max_depth', 1, 30)
        
        # rf = RandomForestClassifier(n_estimators=n_estimators,
        #                 max_leaf_nodes=max_leaf_nodes,
        #                 max_depth=max_depth)
        
        
        
        # KNeighborsClassifier
        
        n_neighbors = trial.suggest_int('n_neighbors', 1, 200)
        leaf_size = trial.suggest_int('leaf_size', 1, 800)
        p = trial.suggest_int('p', 1, 3)
        
        rf = KNeighborsClassifier(n_neighbors=n_neighbors,
                                  leaf_size=leaf_size,
                                  p=p)

        score = cross_val_score(rf, X, y, n_jobs=4, cv=5, scoring='roc_auc', error_score='raise')
        
        display('score.mean(): ', score)
        return score.mean()

    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=200)
    
    return study.best_params

# Study 1 (no ph + remove outlier + aggregate values, 100 trials): 0.1564147933997004
# Study 2 (no preprocessing, 100 trials): 0.12094767907088448
# Study 3 (preprocessing kudos to MOHAMMAD RAZEGHI, 200 trials): 0.18433600629551264
# Study 4 (same as 3 but max_depth allowed to be 1, 
# {'n_estimators': 31, 'learning_rate': 0.15241724886836167, 'max_depth': 1}): 0.22565032154969472

# *begin using roc_auc

# Study 5 ({'n_estimators': 109, 'learning_rate': 0.03160535667677366, 'max_depth': 1}): 0.7891310192305856
# Study 6 [I 2023-04-15 17:47:02,473] Trial 199 finished with value: 0.756868939982877 and parameters: {'n_estimators': 70, 'learning_rate': 0.21972623175664083, 'max_depth': 2}. Best is trial 196 with value: 0.7902962715736496.

print('hello')
# display(np.count_nonzero(np.isnan(X)))

best_params = optuna_study(X, y)

display(best_params)

[I 2023-04-16 12:29:35,631] A new study created in memory with name: no-name-4e5f3593-aa24-40e3-b5a5-c91f1906e327


hello


'score.mean(): '

array([0.74911868, 0.79024677, 0.83783784, 0.84488837, 0.7285628 ])

[I 2023-04-16 12:29:39,795] Trial 0 finished with value: 0.7901308917613263 and parameters: {'n_neighbors': 21, 'leaf_size': 542, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.73472385, 0.77761457, 0.83783784, 0.84958872, 0.72071256])

[I 2023-04-16 12:29:39,817] Trial 1 finished with value: 0.7840955085520303 and parameters: {'n_neighbors': 10, 'leaf_size': 421, 'p': 1}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.67508813, 0.64306698, 0.84547591, 0.69153937, 0.69504831])

[I 2023-04-16 12:29:39,933] Trial 2 finished with value: 0.7100437393915655 and parameters: {'n_neighbors': 190, 'leaf_size': 378, 'p': 3}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74882491, 0.77820212, 0.84224442, 0.8266745 , 0.73399758])

[I 2023-04-16 12:29:39,960] Trial 3 finished with value: 0.7859887060974018 and parameters: {'n_neighbors': 33, 'leaf_size': 230, 'p': 3}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.72150411, 0.76880141, 0.83783784, 0.80875441, 0.7071256 ])

[I 2023-04-16 12:29:39,995] Trial 4 finished with value: 0.7688046742394568 and parameters: {'n_neighbors': 71, 'leaf_size': 222, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.7132785 , 0.68654524, 0.85135135, 0.74500588, 0.71105072])

[I 2023-04-16 12:29:40,043] Trial 5 finished with value: 0.7414463376419899 and parameters: {'n_neighbors': 144, 'leaf_size': 711, 'p': 3}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.71386604, 0.74294947, 0.8907168 , 0.7793772 , 0.72705314])

[I 2023-04-16 12:29:40,087] Trial 6 finished with value: 0.7707925316620968 and parameters: {'n_neighbors': 191, 'leaf_size': 365, 'p': 1}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74294947, 0.75616921, 0.83519389, 0.81081081, 0.71014493])

[I 2023-04-16 12:29:40,115] Trial 7 finished with value: 0.7710536623580102 and parameters: {'n_neighbors': 90, 'leaf_size': 111, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.7479436 , 0.73149236, 0.8140423 , 0.82285546, 0.69836957])

[I 2023-04-16 12:29:40,146] Trial 8 finished with value: 0.7629406580493537 and parameters: {'n_neighbors': 5, 'leaf_size': 10, 'p': 3}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74911868, 0.79024677, 0.83783784, 0.84488837, 0.7285628 ])

[I 2023-04-16 12:29:40,173] Trial 9 finished with value: 0.7901308917613263 and parameters: {'n_neighbors': 21, 'leaf_size': 588, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74412456, 0.77849589, 0.86780259, 0.80934195, 0.71769324])

[I 2023-04-16 12:29:40,219] Trial 10 finished with value: 0.7834916438177307 and parameters: {'n_neighbors': 57, 'leaf_size': 756, 'p': 1}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74735605, 0.78730905, 0.84900118, 0.82403055, 0.71980676])

[I 2023-04-16 12:29:40,262] Trial 11 finished with value: 0.7855007181094138 and parameters: {'n_neighbors': 47, 'leaf_size': 581, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74559342, 0.75646298, 0.83313749, 0.81169213, 0.72403382])

[I 2023-04-16 12:29:40,303] Trial 12 finished with value: 0.774183966575271 and parameters: {'n_neighbors': 113, 'leaf_size': 567, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74970623, 0.78025852, 0.84371328, 0.84077556, 0.73218599])

[I 2023-04-16 12:29:40,345] Trial 13 finished with value: 0.7893279148713931 and parameters: {'n_neighbors': 29, 'leaf_size': 558, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74706228, 0.74059929, 0.84988249, 0.78819036, 0.71256039])

[I 2023-04-16 12:29:40,391] Trial 14 finished with value: 0.7676589633111373 and parameters: {'n_neighbors': 126, 'leaf_size': 638, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74823737, 0.76057579, 0.88631022, 0.81786134, 0.72342995])

[I 2023-04-16 12:29:40,435] Trial 15 finished with value: 0.787282935109022 and parameters: {'n_neighbors': 90, 'leaf_size': 479, 'p': 1}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74001175, 0.79759107, 0.83607521, 0.84224442, 0.72705314])

[I 2023-04-16 12:29:40,478] Trial 16 finished with value: 0.7885951168559864 and parameters: {'n_neighbors': 23, 'leaf_size': 794, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74412456, 0.76880141, 0.82256169, 0.81433608, 0.70772947])

[I 2023-04-16 12:29:40,527] Trial 17 finished with value: 0.7715106410758585 and parameters: {'n_neighbors': 67, 'leaf_size': 650, 'p': 3}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74529965, 0.7846651 , 0.85487662, 0.83431257, 0.72795894])

[I 2023-04-16 12:29:40,567] Trial 18 finished with value: 0.7894225747486618 and parameters: {'n_neighbors': 42, 'leaf_size': 479, 'p': 1}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.71269095, 0.69917744, 0.87749706, 0.72972973, 0.7294686 ])

[I 2023-04-16 12:29:40,610] Trial 19 finished with value: 0.7497127562344954 and parameters: {'n_neighbors': 154, 'leaf_size': 492, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.56139835, 0.64776733, 0.63983549, 0.7153349 , 0.54045894])

[I 2023-04-16 12:29:40,650] Trial 20 finished with value: 0.6209590024807417 and parameters: {'n_neighbors': 1, 'leaf_size': 271, 'p': 2}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.74529965, 0.7846651 , 0.85487662, 0.83431257, 0.72795894])

[I 2023-04-16 12:29:40,693] Trial 21 finished with value: 0.7894225747486618 and parameters: {'n_neighbors': 42, 'leaf_size': 479, 'p': 1}. Best is trial 0 with value: 0.7901308917613263.


'score.mean(): '

array([0.75      , 0.78613396, 0.85340776, 0.84224442, 0.73097826])

[I 2023-04-16 12:29:40,734] Trial 22 finished with value: 0.7925528789659225 and parameters: {'n_neighbors': 24, 'leaf_size': 666, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.74148061, 0.78965922, 0.85752056, 0.8413631 , 0.72161836])

[I 2023-04-16 12:29:40,776] Trial 23 finished with value: 0.7903283718501111 and parameters: {'n_neighbors': 20, 'leaf_size': 683, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.7353114 , 0.77643948, 0.86809636, 0.81022327, 0.72554348])

[I 2023-04-16 12:29:40,840] Trial 24 finished with value: 0.7831227967097532 and parameters: {'n_neighbors': 71, 'leaf_size': 663, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.74206816, 0.78877791, 0.84753231, 0.84371328, 0.72584541])

[I 2023-04-16 12:29:40,885] Trial 25 finished with value: 0.789587413500457 and parameters: {'n_neighbors': 17, 'leaf_size': 698, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.74588719, 0.77526439, 0.86075206, 0.82109283, 0.71286232])

[I 2023-04-16 12:29:40,934] Trial 26 finished with value: 0.783171758715237 and parameters: {'n_neighbors': 55, 'leaf_size': 745, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.73648649, 0.79465335, 0.84312573, 0.84253819, 0.72705314])

[I 2023-04-16 12:29:40,977] Trial 27 finished with value: 0.7887713800757279 and parameters: {'n_neighbors': 38, 'leaf_size': 631, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.74764982, 0.76321974, 0.88542891, 0.81962397, 0.73128019])

[I 2023-04-16 12:29:41,026] Trial 28 finished with value: 0.7894405274840057 and parameters: {'n_neighbors': 86, 'leaf_size': 533, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.74559342, 0.78172738, 0.83431257, 0.84958872, 0.73128019])

[I 2023-04-16 12:29:41,065] Trial 29 finished with value: 0.7885004569787177 and parameters: {'n_neighbors': 12, 'leaf_size': 427, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.74676851, 0.77438308, 0.86574618, 0.80728555, 0.71769324])

[I 2023-04-16 12:29:41,108] Trial 30 finished with value: 0.7823753100927014 and parameters: {'n_neighbors': 58, 'leaf_size': 799, 'p': 1}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.74353702, 0.79347826, 0.83871915, 0.84929495, 0.73248792])

[I 2023-04-16 12:29:41,154] Trial 31 finished with value: 0.791503459981721 and parameters: {'n_neighbors': 20, 'leaf_size': 586, 'p': 2}. Best is trial 22 with value: 0.7925528789659225.


'score.mean(): '

array([0.7479436 , 0.78642773, 0.85105758, 0.8560517 , 0.73611111])

[I 2023-04-16 12:29:41,196] Trial 32 finished with value: 0.7955183444313879 and parameters: {'n_neighbors': 12, 'leaf_size': 708, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.53965922, 0.64776733, 0.62896592, 0.7153349 , 0.52958937])

[I 2023-04-16 12:29:41,239] Trial 33 finished with value: 0.6122633503068287 and parameters: {'n_neighbors': 1, 'leaf_size': 715, 'p': 3}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.7300235 , 0.79142186, 0.84430082, 0.85428907, 0.73097826])

[I 2023-04-16 12:29:41,278] Trial 34 finished with value: 0.7902027027027028 and parameters: {'n_neighbors': 18, 'leaf_size': 610, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.73266745, 0.78789659, 0.84400705, 0.82608696, 0.72735507])

[I 2023-04-16 12:29:41,325] Trial 35 finished with value: 0.7836026243634939 and parameters: {'n_neighbors': 26, 'leaf_size': 677, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.73501763, 0.78584019, 0.84400705, 0.83548766, 0.73429952])

[I 2023-04-16 12:29:41,368] Trial 36 finished with value: 0.786930408669539 and parameters: {'n_neighbors': 31, 'leaf_size': 748, 'p': 3}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.74412456, 0.78848414, 0.84165687, 0.84547591, 0.73550725])

[I 2023-04-16 12:29:41,414] Trial 37 finished with value: 0.7910497453975716 and parameters: {'n_neighbors': 11, 'leaf_size': 691, 'p': 1}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.70094007, 0.69124559, 0.86780259, 0.74236193, 0.7080314 ])

[I 2023-04-16 12:29:41,463] Trial 38 finished with value: 0.7420763154458807 and parameters: {'n_neighbors': 164, 'leaf_size': 520, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.74236193, 0.78143361, 0.84048179, 0.85487662, 0.74124396])

[I 2023-04-16 12:29:41,502] Trial 39 finished with value: 0.7920795795795796 and parameters: {'n_neighbors': 11, 'leaf_size': 723, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.75352526, 0.78231492, 0.84195065, 0.84430082, 0.73429952])

[I 2023-04-16 12:29:41,549] Trial 40 finished with value: 0.7912782347564956 and parameters: {'n_neighbors': 34, 'leaf_size': 350, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.75352526, 0.78231492, 0.84195065, 0.84430082, 0.73429952])

[I 2023-04-16 12:29:41,594] Trial 41 finished with value: 0.7912782347564956 and parameters: {'n_neighbors': 34, 'leaf_size': 314, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.74236193, 0.78143361, 0.84048179, 0.85487662, 0.74124396])

[I 2023-04-16 12:29:41,636] Trial 42 finished with value: 0.7920795795795796 and parameters: {'n_neighbors': 11, 'leaf_size': 341, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.74206816, 0.79054054, 0.83519389, 0.86280846, 0.72373188])

[I 2023-04-16 12:29:41,678] Trial 43 finished with value: 0.7908685859772817 and parameters: {'n_neighbors': 10, 'leaf_size': 144, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.74236193, 0.78143361, 0.84048179, 0.85487662, 0.74124396])

[I 2023-04-16 12:29:41,720] Trial 44 finished with value: 0.7920795795795796 and parameters: {'n_neighbors': 11, 'leaf_size': 397, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.74030552, 0.78848414, 0.82843713, 0.846651  , 0.71074879])

[I 2023-04-16 12:29:41,763] Trial 45 finished with value: 0.7829253166209689 and parameters: {'n_neighbors': 9, 'leaf_size': 414, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.75470035, 0.78554642, 0.83754407, 0.82432432, 0.71256039])

[I 2023-04-16 12:29:41,829] Trial 46 finished with value: 0.7829351090220656 and parameters: {'n_neighbors': 47, 'leaf_size': 320, 'p': 3}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.74030552, 0.74823737, 0.8266745 , 0.85282021, 0.73520531])

[I 2023-04-16 12:29:41,871] Trial 47 finished with value: 0.7806485833659746 and parameters: {'n_neighbors': 7, 'leaf_size': 179, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.69271445, 0.67596945, 0.85428907, 0.74383079, 0.72614734])

[I 2023-04-16 12:29:41,940] Trial 48 finished with value: 0.738590220655438 and parameters: {'n_neighbors': 175, 'leaf_size': 388, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.73237368, 0.78495887, 0.85105758, 0.83166863, 0.72916667])

[I 2023-04-16 12:29:41,992] Trial 49 finished with value: 0.7858450842146494 and parameters: {'n_neighbors': 27, 'leaf_size': 440, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.73619271, 0.76321974, 0.82638073, 0.80376028, 0.71225845])

[I 2023-04-16 12:29:42,046] Trial 50 finished with value: 0.7683623841232536 and parameters: {'n_neighbors': 110, 'leaf_size': 265, 'p': 3}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.73237368, 0.79318449, 0.84341951, 0.86192714, 0.73097826])

[I 2023-04-16 12:29:42,086] Trial 51 finished with value: 0.7923766157461809 and parameters: {'n_neighbors': 17, 'leaf_size': 598, 'p': 2}. Best is trial 32 with value: 0.7955183444313879.


'score.mean(): '

array([0.75      , 0.78877791, 0.84811986, 0.85663925, 0.73822464])

[I 2023-04-16 12:29:42,131] Trial 52 finished with value: 0.7963523305914609 and parameters: {'n_neighbors': 15, 'leaf_size': 736, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.7793772 , 0.83049354, 0.8140423 , 0.71346618])

[I 2023-04-16 12:29:42,171] Trial 53 finished with value: 0.7771233189711451 and parameters: {'n_neighbors': 51, 'leaf_size': 726, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.789953  , 0.84635723, 0.85428907, 0.73550725])

[I 2023-04-16 12:29:42,214] Trial 54 finished with value: 0.7931649040344693 and parameters: {'n_neighbors': 16, 'leaf_size': 782, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74970623, 0.78025852, 0.84371328, 0.84077556, 0.73218599])

[I 2023-04-16 12:29:42,261] Trial 55 finished with value: 0.7893279148713931 and parameters: {'n_neighbors': 29, 'leaf_size': 766, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.56139835, 0.64776733, 0.63983549, 0.7153349 , 0.54045894])

[I 2023-04-16 12:29:42,300] Trial 56 finished with value: 0.6209590024807417 and parameters: {'n_neighbors': 1, 'leaf_size': 783, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74294947, 0.76762632, 0.82784959, 0.8172738 , 0.70591787])

[I 2023-04-16 12:29:42,347] Trial 57 finished with value: 0.7723234103668887 and parameters: {'n_neighbors': 63, 'leaf_size': 612, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73149236, 0.75881316, 0.84576968, 0.81316099, 0.71437198])

[I 2023-04-16 12:29:42,391] Trial 58 finished with value: 0.7727216346781565 and parameters: {'n_neighbors': 82, 'leaf_size': 728, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7353114 , 0.72708578, 0.85487662, 0.78584019, 0.7192029 ])

[I 2023-04-16 12:29:42,469] Trial 59 finished with value: 0.7644633764198983 and parameters: {'n_neighbors': 135, 'leaf_size': 771, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76057579, 0.78760282, 0.84811986, 0.83813161, 0.72403382])

[I 2023-04-16 12:29:42,517] Trial 60 finished with value: 0.7916927797362581 and parameters: {'n_neighbors': 38, 'leaf_size': 654, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73237368, 0.79318449, 0.84341951, 0.86192714, 0.73097826])

[I 2023-04-16 12:29:42,561] Trial 61 finished with value: 0.7923766157461809 and parameters: {'n_neighbors': 17, 'leaf_size': 737, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73296122, 0.79347826, 0.84753231, 0.84723854, 0.73550725])

[I 2023-04-16 12:29:42,609] Trial 62 finished with value: 0.7913435174304739 and parameters: {'n_neighbors': 19, 'leaf_size': 716, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74559342, 0.79524089, 0.83108108, 0.83254994, 0.73097826])

[I 2023-04-16 12:29:42,657] Trial 63 finished with value: 0.7870887191539365 and parameters: {'n_neighbors': 24, 'leaf_size': 743, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73237368, 0.79318449, 0.84341951, 0.86192714, 0.73097826])

[I 2023-04-16 12:29:42,703] Trial 64 finished with value: 0.7923766157461809 and parameters: {'n_neighbors': 17, 'leaf_size': 628, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73237368, 0.79318449, 0.84341951, 0.86192714, 0.73097826])

[I 2023-04-16 12:29:42,749] Trial 65 finished with value: 0.7923766157461809 and parameters: {'n_neighbors': 17, 'leaf_size': 619, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75088132, 0.79024677, 0.84430082, 0.82608696, 0.72433575])

[I 2023-04-16 12:29:42,796] Trial 66 finished with value: 0.7871703224964095 and parameters: {'n_neighbors': 43, 'leaf_size': 666, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73913043, 0.73443008, 0.80229142, 0.84018801, 0.70018116])

[I 2023-04-16 12:29:42,848] Trial 67 finished with value: 0.7632442224833529 and parameters: {'n_neighbors': 5, 'leaf_size': 561, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73883666, 0.78848414, 0.82814336, 0.83666275, 0.7294686 ])

[I 2023-04-16 12:29:42,931] Trial 68 finished with value: 0.784319101710406 and parameters: {'n_neighbors': 24, 'leaf_size': 696, 'p': 3}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76703878, 0.78231492, 0.84547591, 0.83548766, 0.7294686 ])

[I 2023-04-16 12:29:43,032] Trial 69 finished with value: 0.7919571745658703 and parameters: {'n_neighbors': 37, 'leaf_size': 652, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73237368, 0.78495887, 0.85105758, 0.83166863, 0.72916667])

[I 2023-04-16 12:29:43,086] Trial 70 finished with value: 0.7858450842146494 and parameters: {'n_neighbors': 27, 'leaf_size': 756, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74911868, 0.79024677, 0.83783784, 0.84488837, 0.7285628 ])

[I 2023-04-16 12:29:43,133] Trial 71 finished with value: 0.7901308917613263 and parameters: {'n_neighbors': 21, 'leaf_size': 615, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.69300823, 0.72150411, 0.79612221, 0.82285546, 0.69353865])

[I 2023-04-16 12:29:43,176] Trial 72 finished with value: 0.7454057318187755 and parameters: {'n_neighbors': 4, 'leaf_size': 15, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.789953  , 0.84635723, 0.85428907, 0.73550725])

[I 2023-04-16 12:29:43,225] Trial 73 finished with value: 0.7931649040344693 and parameters: {'n_neighbors': 16, 'leaf_size': 633, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73237368, 0.79318449, 0.84341951, 0.86192714, 0.73097826])

[I 2023-04-16 12:29:43,275] Trial 74 finished with value: 0.7923766157461809 and parameters: {'n_neighbors': 17, 'leaf_size': 591, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75058754, 0.78525264, 0.83960047, 0.85546416, 0.74245169])

[I 2023-04-16 12:29:43,329] Trial 75 finished with value: 0.7946713017365192 and parameters: {'n_neighbors': 14, 'leaf_size': 694, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.65599295, 0.66274971, 0.86045828, 0.70475911, 0.6977657 ])

[I 2023-04-16 12:29:43,384] Trial 76 finished with value: 0.7163451494973234 and parameters: {'n_neighbors': 199, 'leaf_size': 685, 'p': 2}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:43,434] Trial 77 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 796, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.79700353, 0.84077556, 0.83842538, 0.73278986])

[I 2023-04-16 12:29:43,485] Trial 78 finished with value: 0.7914463376419899 and parameters: {'n_neighbors': 31, 'leaf_size': 784, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:43,533] Trial 79 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 708, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73266745, 0.76233843, 0.82373678, 0.85076381, 0.7071256 ])

[I 2023-04-16 12:29:43,584] Trial 80 finished with value: 0.7753264133698916 and parameters: {'n_neighbors': 6, 'leaf_size': 796, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74559342, 0.78172738, 0.83431257, 0.84958872, 0.73128019])

[I 2023-04-16 12:29:43,633] Trial 81 finished with value: 0.7885004569787177 and parameters: {'n_neighbors': 12, 'leaf_size': 706, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:43,673] Trial 82 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 678, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.56139835, 0.64776733, 0.653349  , 0.7153349 , 0.54045894])

[I 2023-04-16 12:29:43,723] Trial 83 finished with value: 0.6236617051834443 and parameters: {'n_neighbors': 1, 'leaf_size': 674, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74294947, 0.78642773, 0.83901293, 0.84900118, 0.72705314])

[I 2023-04-16 12:29:43,770] Trial 84 finished with value: 0.7888888888888889 and parameters: {'n_neighbors': 13, 'leaf_size': 764, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75      , 0.78613396, 0.85340776, 0.84224442, 0.73097826])

[I 2023-04-16 12:29:43,815] Trial 85 finished with value: 0.7925528789659225 and parameters: {'n_neighbors': 24, 'leaf_size': 696, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.79700353, 0.84077556, 0.83842538, 0.73278986])

[I 2023-04-16 12:29:43,896] Trial 86 finished with value: 0.7914463376419899 and parameters: {'n_neighbors': 31, 'leaf_size': 646, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73707403, 0.76410106, 0.82520564, 0.84753231, 0.71437198])

[I 2023-04-16 12:29:43,941] Trial 87 finished with value: 0.7776570048309179 and parameters: {'n_neighbors': 7, 'leaf_size': 745, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:44,001] Trial 88 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 774, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:44,058] Trial 89 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 783, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73266745, 0.78907168, 0.84782609, 0.84077556, 0.73550725])

[I 2023-04-16 12:29:44,112] Trial 90 finished with value: 0.7891696043869956 and parameters: {'n_neighbors': 35, 'leaf_size': 778, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:44,161] Trial 91 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 796, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74294947, 0.78642773, 0.83901293, 0.84900118, 0.72705314])

[I 2023-04-16 12:29:44,210] Trial 92 finished with value: 0.7888888888888889 and parameters: {'n_neighbors': 13, 'leaf_size': 763, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73707403, 0.76410106, 0.82520564, 0.84753231, 0.71437198])

[I 2023-04-16 12:29:44,262] Trial 93 finished with value: 0.7776570048309179 and parameters: {'n_neighbors': 7, 'leaf_size': 799, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.78349001, 0.85987074, 0.84518214, 0.73067633])

[I 2023-04-16 12:29:44,315] Trial 94 finished with value: 0.7917874396135265 and parameters: {'n_neighbors': 23, 'leaf_size': 714, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:44,363] Trial 95 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 748, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74383079, 0.78730905, 0.85282021, 0.83695652, 0.72554348])

[I 2023-04-16 12:29:44,407] Trial 96 finished with value: 0.7892920094007051 and parameters: {'n_neighbors': 41, 'leaf_size': 734, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.56139835, 0.64776733, 0.653349  , 0.7153349 , 0.54045894])

[I 2023-04-16 12:29:44,458] Trial 97 finished with value: 0.6236617051834443 and parameters: {'n_neighbors': 1, 'leaf_size': 800, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73413631, 0.80170388, 0.8393067 , 0.84459459, 0.7388285 ])

[I 2023-04-16 12:29:44,503] Trial 98 finished with value: 0.791713996605301 and parameters: {'n_neighbors': 30, 'leaf_size': 746, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.79700353, 0.85517039, 0.84253819, 0.72342995])

[I 2023-04-16 12:29:44,554] Trial 99 finished with value: 0.7915720067893981 and parameters: {'n_neighbors': 21, 'leaf_size': 763, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74294947, 0.78642773, 0.83901293, 0.84900118, 0.72705314])

[I 2023-04-16 12:29:44,599] Trial 100 finished with value: 0.7888888888888889 and parameters: {'n_neighbors': 13, 'leaf_size': 726, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7153349 , 0.77555817, 0.84106933, 0.8592832 , 0.71135266])

[I 2023-04-16 12:29:44,648] Trial 101 finished with value: 0.7805196500848675 and parameters: {'n_neighbors': 8, 'leaf_size': 782, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74882491, 0.7552879 , 0.87955347, 0.81756757, 0.727657  ])

[I 2023-04-16 12:29:44,700] Trial 102 finished with value: 0.7857781694738217 and parameters: {'n_neighbors': 101, 'leaf_size': 776, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:44,742] Trial 103 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 709, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74559342, 0.8046416 , 0.8413631 , 0.85017626, 0.73128019])

[I 2023-04-16 12:29:44,796] Trial 104 finished with value: 0.7946109152630891 and parameters: {'n_neighbors': 27, 'leaf_size': 706, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73266745, 0.76233843, 0.82373678, 0.85076381, 0.7071256 ])

[I 2023-04-16 12:29:44,841] Trial 105 finished with value: 0.7753264133698916 and parameters: {'n_neighbors': 6, 'leaf_size': 684, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74294947, 0.78642773, 0.83901293, 0.84900118, 0.72705314])

[I 2023-04-16 12:29:44,893] Trial 106 finished with value: 0.7888888888888889 and parameters: {'n_neighbors': 13, 'leaf_size': 757, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.79700353, 0.85517039, 0.84253819, 0.72342995])

[I 2023-04-16 12:29:44,941] Trial 107 finished with value: 0.7915720067893981 and parameters: {'n_neighbors': 21, 'leaf_size': 736, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.70005875, 0.70652174, 0.75146886, 0.77820212, 0.69051932])

[I 2023-04-16 12:29:44,990] Trial 108 finished with value: 0.7253541585063324 and parameters: {'n_neighbors': 3, 'leaf_size': 712, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7153349 , 0.77555817, 0.84106933, 0.8592832 , 0.71135266])

[I 2023-04-16 12:29:45,039] Trial 109 finished with value: 0.7805196500848675 and parameters: {'n_neighbors': 8, 'leaf_size': 669, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:45,091] Trial 110 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 754, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:45,137] Trial 111 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 746, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.79700353, 0.85517039, 0.84253819, 0.72342995])

[I 2023-04-16 12:29:45,190] Trial 112 finished with value: 0.7915720067893981 and parameters: {'n_neighbors': 21, 'leaf_size': 758, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74529965, 0.79612221, 0.84430082, 0.84606345, 0.73913043])

[I 2023-04-16 12:29:45,241] Trial 113 finished with value: 0.7941833137485312 and parameters: {'n_neighbors': 26, 'leaf_size': 721, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73472385, 0.77761457, 0.83783784, 0.84958872, 0.72071256])

[I 2023-04-16 12:29:45,291] Trial 114 finished with value: 0.7840955085520303 and parameters: {'n_neighbors': 10, 'leaf_size': 743, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73354877, 0.78495887, 0.83225617, 0.83607521, 0.7201087 ])

[I 2023-04-16 12:29:45,345] Trial 115 finished with value: 0.7813895417156287 and parameters: {'n_neighbors': 18, 'leaf_size': 781, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.72943596, 0.77555817, 0.83490012, 0.8560517 , 0.71256039])

[I 2023-04-16 12:29:45,396] Trial 116 finished with value: 0.7817012664838753 and parameters: {'n_neighbors': 9, 'leaf_size': 772, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73384254, 0.7826087 , 0.83871915, 0.84488837, 0.74003623])

[I 2023-04-16 12:29:45,450] Trial 117 finished with value: 0.7880189972581279 and parameters: {'n_neighbors': 33, 'leaf_size': 732, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7027027 , 0.71768508, 0.77908343, 0.82784959, 0.6884058 ])

[I 2023-04-16 12:29:45,501] Trial 118 finished with value: 0.7431453192322757 and parameters: {'n_neighbors': 4, 'leaf_size': 752, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75293772, 0.75616921, 0.88307873, 0.80229142, 0.7201087 ])

[I 2023-04-16 12:29:45,552] Trial 119 finished with value: 0.7829171562867215 and parameters: {'n_neighbors': 125, 'leaf_size': 786, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:45,633] Trial 120 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 708, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:45,679] Trial 121 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 701, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:45,734] Trial 122 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 722, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74148061, 0.78965922, 0.85752056, 0.8413631 , 0.72161836])

[I 2023-04-16 12:29:45,802] Trial 123 finished with value: 0.7903283718501111 and parameters: {'n_neighbors': 20, 'leaf_size': 800, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73766157, 0.80405405, 0.84341951, 0.84547591, 0.73550725])

[I 2023-04-16 12:29:45,860] Trial 124 finished with value: 0.7932236584410498 and parameters: {'n_neighbors': 28, 'leaf_size': 727, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.79289072, 0.84841363, 0.85223267, 0.72644928])

[I 2023-04-16 12:29:45,907] Trial 125 finished with value: 0.7936447316882099 and parameters: {'n_neighbors': 16, 'leaf_size': 749, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73648649, 0.78877791, 0.85634548, 0.83666275, 0.73128019])

[I 2023-04-16 12:29:45,956] Trial 126 finished with value: 0.7899105627366498 and parameters: {'n_neighbors': 22, 'leaf_size': 769, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.72943596, 0.77555817, 0.83490012, 0.8560517 , 0.71256039])

[I 2023-04-16 12:29:46,003] Trial 127 finished with value: 0.7817012664838753 and parameters: {'n_neighbors': 9, 'leaf_size': 679, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75058754, 0.7993537 , 0.84988249, 0.84106933, 0.73278986])

[I 2023-04-16 12:29:46,067] Trial 128 finished with value: 0.7947365844104974 and parameters: {'n_neighbors': 25, 'leaf_size': 722, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:46,122] Trial 129 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 757, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73178613, 0.78907168, 0.84077556, 0.83548766, 0.72161836])

[I 2023-04-16 12:29:46,178] Trial 130 finished with value: 0.7837478783130957 and parameters: {'n_neighbors': 19, 'leaf_size': 766, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:46,233] Trial 131 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 739, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7027027 , 0.71768508, 0.77908343, 0.82784959, 0.6884058 ])

[I 2023-04-16 12:29:46,274] Trial 132 finished with value: 0.7431453192322757 and parameters: {'n_neighbors': 4, 'leaf_size': 713, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:46,332] Trial 133 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 788, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73354877, 0.76086957, 0.87837838, 0.81815511, 0.73460145])

[I 2023-04-16 12:29:46,386] Trial 134 finished with value: 0.7851106541323933 and parameters: {'n_neighbors': 79, 'leaf_size': 693, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74412456, 0.78848414, 0.84165687, 0.84547591, 0.73550725])

[I 2023-04-16 12:29:46,435] Trial 135 finished with value: 0.7910497453975716 and parameters: {'n_neighbors': 11, 'leaf_size': 734, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73354877, 0.78495887, 0.83225617, 0.83607521, 0.7201087 ])

[I 2023-04-16 12:29:46,486] Trial 136 finished with value: 0.7813895417156287 and parameters: {'n_neighbors': 18, 'leaf_size': 660, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75      , 0.78613396, 0.85340776, 0.84224442, 0.73097826])

[I 2023-04-16 12:29:46,536] Trial 137 finished with value: 0.7925528789659225 and parameters: {'n_neighbors': 24, 'leaf_size': 756, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73707403, 0.76410106, 0.82520564, 0.84753231, 0.71437198])

[I 2023-04-16 12:29:46,580] Trial 138 finished with value: 0.7776570048309179 and parameters: {'n_neighbors': 7, 'leaf_size': 771, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.56139835, 0.64776733, 0.653349  , 0.7153349 , 0.54045894])

[I 2023-04-16 12:29:46,629] Trial 139 finished with value: 0.6236617051834443 and parameters: {'n_neighbors': 1, 'leaf_size': 458, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73560517, 0.80552291, 0.84312573, 0.85047004, 0.73369565])

[I 2023-04-16 12:29:46,687] Trial 140 finished with value: 0.7936839012925969 and parameters: {'n_neighbors': 29, 'leaf_size': 800, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:46,734] Trial 141 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 740, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:46,785] Trial 142 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 741, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73178613, 0.78907168, 0.84077556, 0.83548766, 0.72161836])

[I 2023-04-16 12:29:46,833] Trial 143 finished with value: 0.7837478783130957 and parameters: {'n_neighbors': 19, 'leaf_size': 707, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73472385, 0.77761457, 0.83783784, 0.84958872, 0.72071256])

[I 2023-04-16 12:29:46,886] Trial 144 finished with value: 0.7840955085520303 and parameters: {'n_neighbors': 10, 'leaf_size': 740, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.78349001, 0.85987074, 0.84518214, 0.73067633])

[I 2023-04-16 12:29:46,938] Trial 145 finished with value: 0.7917874396135265 and parameters: {'n_neighbors': 23, 'leaf_size': 506, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:46,996] Trial 146 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 724, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74206816, 0.78877791, 0.84753231, 0.84371328, 0.72584541])

[I 2023-04-16 12:29:47,043] Trial 147 finished with value: 0.789587413500457 and parameters: {'n_neighbors': 17, 'leaf_size': 732, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74030552, 0.74882491, 0.89659224, 0.806698  , 0.73671498])

[I 2023-04-16 12:29:47,139] Trial 148 finished with value: 0.7858271314793054 and parameters: {'n_neighbors': 154, 'leaf_size': 780, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.72473561, 0.74559342, 0.79112808, 0.8487074 , 0.71135266])

[I 2023-04-16 12:29:47,198] Trial 149 finished with value: 0.7643034338686514 and parameters: {'n_neighbors': 5, 'leaf_size': 688, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73472385, 0.77761457, 0.83783784, 0.84958872, 0.72071256])

[I 2023-04-16 12:29:47,249] Trial 150 finished with value: 0.7840955085520303 and parameters: {'n_neighbors': 10, 'leaf_size': 720, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:47,305] Trial 151 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 706, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.79700353, 0.85517039, 0.84253819, 0.72342995])

[I 2023-04-16 12:29:47,358] Trial 152 finished with value: 0.7915720067893981 and parameters: {'n_neighbors': 21, 'leaf_size': 765, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.79289072, 0.84841363, 0.85223267, 0.72644928])

[I 2023-04-16 12:29:47,402] Trial 153 finished with value: 0.7936447316882099 and parameters: {'n_neighbors': 16, 'leaf_size': 740, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74529965, 0.79612221, 0.84430082, 0.84606345, 0.73913043])

[I 2023-04-16 12:29:47,452] Trial 154 finished with value: 0.7941833137485312 and parameters: {'n_neighbors': 26, 'leaf_size': 678, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74412456, 0.78848414, 0.84165687, 0.84547591, 0.73550725])

[I 2023-04-16 12:29:47,504] Trial 155 finished with value: 0.7910497453975716 and parameters: {'n_neighbors': 11, 'leaf_size': 753, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73707403, 0.76410106, 0.82520564, 0.84753231, 0.71437198])

[I 2023-04-16 12:29:47,554] Trial 156 finished with value: 0.7776570048309179 and parameters: {'n_neighbors': 7, 'leaf_size': 698, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.70887192, 0.7226792 , 0.89277321, 0.78642773, 0.71859903])

[I 2023-04-16 12:29:47,611] Trial 157 finished with value: 0.765870218044131 and parameters: {'n_neighbors': 181, 'leaf_size': 785, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.79289072, 0.84841363, 0.85223267, 0.72644928])

[I 2023-04-16 12:29:47,669] Trial 158 finished with value: 0.7936447316882099 and parameters: {'n_neighbors': 16, 'leaf_size': 729, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74148061, 0.78965922, 0.85752056, 0.8413631 , 0.72161836])

[I 2023-04-16 12:29:47,726] Trial 159 finished with value: 0.7903283718501111 and parameters: {'n_neighbors': 20, 'leaf_size': 769, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74882491, 0.77820212, 0.84224442, 0.8266745 , 0.73399758])

[I 2023-04-16 12:29:47,781] Trial 160 finished with value: 0.7859887060974018 and parameters: {'n_neighbors': 33, 'leaf_size': 714, 'p': 3}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:47,831] Trial 161 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 705, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:47,881] Trial 162 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 744, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73472385, 0.77761457, 0.83783784, 0.84958872, 0.72071256])

[I 2023-04-16 12:29:47,930] Trial 163 finished with value: 0.7840955085520303 and parameters: {'n_neighbors': 10, 'leaf_size': 719, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73913043, 0.78437133, 0.86075206, 0.84165687, 0.72886473])

[I 2023-04-16 12:29:47,984] Trial 164 finished with value: 0.7909550855203029 and parameters: {'n_neighbors': 23, 'leaf_size': 46, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.72473561, 0.74559342, 0.79112808, 0.8487074 , 0.71135266])

[I 2023-04-16 12:29:48,037] Trial 165 finished with value: 0.7643034338686514 and parameters: {'n_neighbors': 5, 'leaf_size': 669, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74206816, 0.78877791, 0.84753231, 0.84371328, 0.72584541])

[I 2023-04-16 12:29:48,087] Trial 166 finished with value: 0.789587413500457 and parameters: {'n_neighbors': 17, 'leaf_size': 756, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74412456, 0.78848414, 0.84165687, 0.84547591, 0.73550725])

[I 2023-04-16 12:29:48,132] Trial 167 finished with value: 0.7910497453975716 and parameters: {'n_neighbors': 11, 'leaf_size': 690, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74148061, 0.78965922, 0.85752056, 0.8413631 , 0.72161836])

[I 2023-04-16 12:29:48,205] Trial 168 finished with value: 0.7903283718501111 and parameters: {'n_neighbors': 20, 'leaf_size': 789, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74559342, 0.8046416 , 0.8413631 , 0.85017626, 0.73128019])

[I 2023-04-16 12:29:48,248] Trial 169 finished with value: 0.7946109152630891 and parameters: {'n_neighbors': 27, 'leaf_size': 736, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73707403, 0.76410106, 0.82520564, 0.84753231, 0.71437198])

[I 2023-04-16 12:29:48,292] Trial 170 finished with value: 0.7776570048309179 and parameters: {'n_neighbors': 7, 'leaf_size': 644, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74294947, 0.78642773, 0.83901293, 0.84900118, 0.72705314])

[I 2023-04-16 12:29:48,336] Trial 171 finished with value: 0.7888888888888889 and parameters: {'n_neighbors': 13, 'leaf_size': 755, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:48,384] Trial 172 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 766, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74206816, 0.78877791, 0.84753231, 0.84371328, 0.72584541])

[I 2023-04-16 12:29:48,432] Trial 173 finished with value: 0.789587413500457 and parameters: {'n_neighbors': 17, 'leaf_size': 773, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73971798, 0.78349001, 0.85987074, 0.84518214, 0.73067633])

[I 2023-04-16 12:29:48,482] Trial 174 finished with value: 0.7917874396135265 and parameters: {'n_neighbors': 23, 'leaf_size': 721, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74294947, 0.78642773, 0.83901293, 0.84900118, 0.72705314])

[I 2023-04-16 12:29:48,552] Trial 175 finished with value: 0.7888888888888889 and parameters: {'n_neighbors': 13, 'leaf_size': 775, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7027027 , 0.71768508, 0.77908343, 0.82784959, 0.6884058 ])

[I 2023-04-16 12:29:48,616] Trial 176 finished with value: 0.7431453192322757 and parameters: {'n_neighbors': 4, 'leaf_size': 703, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74148061, 0.78965922, 0.85752056, 0.8413631 , 0.72161836])

[I 2023-04-16 12:29:48,680] Trial 177 finished with value: 0.7903283718501111 and parameters: {'n_neighbors': 20, 'leaf_size': 224, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.72943596, 0.77555817, 0.83490012, 0.8560517 , 0.71256039])

[I 2023-04-16 12:29:48,727] Trial 178 finished with value: 0.7817012664838753 and parameters: {'n_neighbors': 9, 'leaf_size': 742, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.79289072, 0.84841363, 0.85223267, 0.72644928])

[I 2023-04-16 12:29:48,774] Trial 179 finished with value: 0.7936447316882099 and parameters: {'n_neighbors': 16, 'leaf_size': 798, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74559342, 0.78172738, 0.83431257, 0.84958872, 0.73128019])

[I 2023-04-16 12:29:48,818] Trial 180 finished with value: 0.7885004569787177 and parameters: {'n_neighbors': 12, 'leaf_size': 543, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:48,862] Trial 181 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 755, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73354877, 0.78495887, 0.83225617, 0.83607521, 0.7201087 ])

[I 2023-04-16 12:29:48,906] Trial 182 finished with value: 0.7813895417156287 and parameters: {'n_neighbors': 18, 'leaf_size': 760, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7153349 , 0.77555817, 0.84106933, 0.8592832 , 0.71135266])

[I 2023-04-16 12:29:48,953] Trial 183 finished with value: 0.7805196500848675 and parameters: {'n_neighbors': 8, 'leaf_size': 730, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:49,015] Trial 184 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 782, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75      , 0.78613396, 0.85340776, 0.84224442, 0.73097826])

[I 2023-04-16 12:29:49,063] Trial 185 finished with value: 0.7925528789659225 and parameters: {'n_neighbors': 24, 'leaf_size': 751, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.56139835, 0.64776733, 0.653349  , 0.7153349 , 0.54045894])

[I 2023-04-16 12:29:49,109] Trial 186 finished with value: 0.6236617051834443 and parameters: {'n_neighbors': 1, 'leaf_size': 710, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74148061, 0.78965922, 0.85752056, 0.8413631 , 0.72161836])

[I 2023-04-16 12:29:49,160] Trial 187 finished with value: 0.7903283718501111 and parameters: {'n_neighbors': 20, 'leaf_size': 731, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74412456, 0.78848414, 0.84165687, 0.84547591, 0.73550725])

[I 2023-04-16 12:29:49,207] Trial 188 finished with value: 0.7910497453975716 and parameters: {'n_neighbors': 11, 'leaf_size': 776, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74823737, 0.79289072, 0.84841363, 0.85223267, 0.72644928])

[I 2023-04-16 12:29:49,256] Trial 189 finished with value: 0.7936447316882099 and parameters: {'n_neighbors': 16, 'leaf_size': 764, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73266745, 0.76233843, 0.82373678, 0.85076381, 0.7071256 ])

[I 2023-04-16 12:29:49,307] Trial 190 finished with value: 0.7753264133698916 and parameters: {'n_neighbors': 6, 'leaf_size': 741, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.76116334, 0.7846651 , 0.85047004, 0.84900118, 0.73520531])

[I 2023-04-16 12:29:49,360] Trial 191 finished with value: 0.7961009922966447 and parameters: {'n_neighbors': 14, 'leaf_size': 760, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74148061, 0.78965922, 0.85752056, 0.8413631 , 0.72161836])

[I 2023-04-16 12:29:49,406] Trial 192 finished with value: 0.7903283718501111 and parameters: {'n_neighbors': 20, 'leaf_size': 720, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73472385, 0.77761457, 0.83783784, 0.84958872, 0.72071256])

[I 2023-04-16 12:29:49,464] Trial 193 finished with value: 0.7840955085520303 and parameters: {'n_neighbors': 10, 'leaf_size': 745, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75969448, 0.79289072, 0.84753231, 0.84694477, 0.73399758])

[I 2023-04-16 12:29:49,516] Trial 194 finished with value: 0.7962119728424077 and parameters: {'n_neighbors': 15, 'leaf_size': 790, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74206816, 0.78877791, 0.84753231, 0.84371328, 0.72584541])

[I 2023-04-16 12:29:49,565] Trial 195 finished with value: 0.789587413500457 and parameters: {'n_neighbors': 17, 'leaf_size': 800, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.75      , 0.78613396, 0.85340776, 0.84224442, 0.73097826])

[I 2023-04-16 12:29:49,608] Trial 196 finished with value: 0.7925528789659225 and parameters: {'n_neighbors': 24, 'leaf_size': 786, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.73766157, 0.80405405, 0.84341951, 0.84547591, 0.73550725])

[I 2023-04-16 12:29:49,656] Trial 197 finished with value: 0.7932236584410498 and parameters: {'n_neighbors': 28, 'leaf_size': 692, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.74559342, 0.78172738, 0.83431257, 0.84958872, 0.73128019])

[I 2023-04-16 12:29:49,702] Trial 198 finished with value: 0.7885004569787177 and parameters: {'n_neighbors': 12, 'leaf_size': 772, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


'score.mean(): '

array([0.7153349 , 0.77555817, 0.84106933, 0.8592832 , 0.71135266])

[I 2023-04-16 12:29:49,748] Trial 199 finished with value: 0.7805196500848675 and parameters: {'n_neighbors': 8, 'leaf_size': 265, 'p': 1}. Best is trial 52 with value: 0.7963523305914609.


{'n_neighbors': 15, 'leaf_size': 736, 'p': 2}

# Submission

In [232]:
# final_model = XGBRegressor(
#     n_estimators = best_params['n_estimators'], 
#     max_depth = best_params['max_depth'], 
#     learning_rate = best_params['learning_rate'],
#     n_jobs=4)

# final_model = RandomForestClassifier(
#     n_estimators = best_params['n_estimators'], 
#     max_leaf_nodes = best_params['max_leaf_nodes'], 
#     max_depth = best_params['max_depth'],
#     n_jobs=4)

final_model = KNeighborsClassifier(
    n_neighbors = best_params['n_neighbors'], 
    leaf_size = best_params['leaf_size'], 
    p = best_params['p'],
    n_jobs=4)

final_model.fit(X, y)
predictions = final_model.predict(no_id_test_data)

submission = pd.DataFrame({'id': test_data.id, 'target': predictions})

display(submission.head())

submission.to_csv(f'submission11.csv', index=False)

print('Successful')

id  target
0  414       0
1  415       1
2  416       0
3  417       0
4  418       0

Successful
